# Site settings
title: larsw wp15
email: lw222ii@student.lnu.se
timezone: Asia/Shanghai
description: > # this means to ignore newlines until "baseurl:"
  Project portfolio & blog for Lars W
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
github_username:  larswww
ico: favicon.ico

# Build settings
markdown: kramdown
